# Generated by Django 3.2.9 on 2021-12-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_alter_person_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
